spring:
  profiles:
    action:
        -dev
      
---  

server: 8081
spring:
  profiles: dev
  application:
    name: micservice-config-dev

---
server: 8082
spring:
  profiles: test
  application:
    name: micservice-config-test
    
---

