spring:
  profiles:
    action:
      
---  
spring:
  profiles: dev
  application:
    name: micservice-config-dev

---
spring:
  profiles: test
  application:
    name: micservice-config-test
    
---

